version: "3.8"
services:
  Nasir:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: User_System
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
      image: adminer
      container_name: adminer
      ports:
      - 8080:8080

volumes:
  mysql_data:

